update tips

diff --git a/fmt-check b/fmt-check
--- a/fmt-check
+++ b/fmt-check
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 test_fmt() {
-    hash gofmt 2>&- || { echo >&2 "gofmt not in PATH."; exit 1; }
+    hash goimports 2>&- || { echo >&2 "goimports not in PATH."; exit 1; }
     IFS='
 '
     for file in `git diff --cached --name-only --diff-filter=ACM | grep '\.go$'`
@@ -19,13 +19,13 @@ test_fmt() {
     exitcode=0
     if test -n "$syntaxerrors"
     then
-        echo >&2 "gofmt found syntax errors:"
+        echo >&2 "goimports found syntax errors:"
         printf "$syntaxerrors"
         exitcode=1
     fi
     if test -n "$list"
     then
-        echo >&2 "gofmt needs to format these files (run gofmt -w and git add):"
+        echo >&2 "goimports needs to format these files (run gofmts -w and git add, or run go-fmt-fix):"
         printf "$list"
         exitcode=1
     fi
